<?php    //edit view
return [
    'config' => [
        'title' => 'Departamentos',
        'subtitle' => 'Modificar registro',
        'action' => 'update',
        'url_action' => '/departamentos/update',
        'method' => 'POST',
        'tipo' => 'form',
        'class_div' => "p-4 bg-light rounded shadow-sm h-100",
        'class_form' => 'row g-4 p-4 bg-light rounded shadow-sm',
        'class_tr' => 'p-4 bg-light rounded shadow-sm h-100',
        'class_th' => 'text-center',
        'class_td' => 'text-center',
        'class_table' => 'table table-striped table-bordered',
        'class_table_div' => 'row g-4 p-4 bg-light shadow-sm',
        'class_thead' => 'thead-light',
        'class_tbody' => 'container',
        'class_tfoot' => 'thead-light',
    ],
    'comandos' => [
        'Nuevo' => [
            'text' => 'Nuevo Departamentos',
            'url' => '/departamentos/create/',
            'icon' => 'bi bi-add',
            'class' => 'btn btn-primary'
        ],
    ],
    'campos' => [
        'nombre' => [
            'nombre' => 'nombre',
            'type' => 'text',
            'label' => 'Nombre',
            'maxlength' => 100,
            'readonly' => false,
            'hidden' => false,
            'required' => false,
            'placeholder' => 'Ingrese Nombre',
            'help' => 'Ingrese Nombre',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
        'cargo_id' => [
            'nombre' => 'cargo_id',
            'type' => 'select',
            'label' => 'Cargo_id',
            'maxlength' => 11,
            'readonly' => false,
            'hidden' => false,
            'required' => false,
            'placeholder' => 'Ingrese Cargo_id',
            'help' => 'Ingrese Cargo_id',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
            'tabla_rel' => 'cargo',
            'options' => [],
        ],
        'descripcion' => [
            'nombre' => 'descripcion',
            'type' => 'textarea',
            'label' => 'Descripcion',
            'maxlength' => 255,
            'readonly' => false,
            'hidden' => false,
            'required' => true,
            'placeholder' => 'Ingrese Descripcion',
            'help' => 'Ingrese Descripcion',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
        'activo' => [
            'nombre' => 'activo',
            'type' => 'number',
            'label' => 'Activo',
            'maxlength' => 1,
            'readonly' => false,
            'hidden' => false,
            'required' => true,
            'placeholder' => 'Ingrese Activo',
            'help' => 'Ingrese Activo',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
        'created_at' => [
            'nombre' => 'created_at',
            'type' => 'text',
            'label' => 'Created_at',
            'maxlength' => 255,
            'readonly' => false,
            'hidden' => false,
            'required' => true,
            'placeholder' => 'Ingrese Created_at',
            'help' => 'Ingrese Created_at',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
    ],
    'actividades' => [
        'delete' => [
            'text' => 'Eliminar',
            'url' => '/departamentos/delete/',
            'icon' => 'bi bi-trash',
            'class' => 'btn btn-danger'
        ]
    ],
    'buttons' => [
        'cancel' => [
            'type' => 'button',
            'text' => 'Volver',
            'url' => '',
            'class' => 'btn btn-outline-secondary btn-rounded',
            'icon' => 'bi bi-arrow-left',
            'backbutton' => true,
        ],
        'submit' => [
            'type' => 'submit',
            'text' => 'Guardar',
            'class' => 'btn btn-gradient btn-rounded',
            'icon' => 'bi bi-check-circle me-1',
        ],
    ],
];
