<?php
/**
 * Application Routes
 */

use Foundation\Core\Router;
use App\Controllers\HomeController;
use App\Controllers\UserController;
use App\Middlewares\AuthMiddleware;

// Home page
Router::get('/', [HomeController::class, 'index']);

// Example CRUD routes (generated by makecrud)
// Router::get('/users', [UserController::class, 'index'], [AuthMiddleware::class]);
// Router::get('/users/create', [UserController::class, 'create'], [AuthMiddleware::class]);
// Router::post('/users/store', [UserController::class, 'store'], [AuthMiddleware::class]);
// Router::get('/users/edit/{id}', [UserController::class, 'edit'], [AuthMiddleware::class]);
// Router::post('/users/update/{id}', [UserController::class, 'update'], [AuthMiddleware::class]);
// Router::get('/users/vista/{id}', [UserController::class, 'vista'], [AuthMiddleware::class]);
// Router::post('/users/delete/{id}', [UserController::class, 'delete'], [AuthMiddleware::class]);
