<?php    //edit view
return [    'config' => [
                'titulo' => 'Datos Personales',
                'subtitulo' => 'Ver detalle',
                'action' => 'update',
                'url_action' => '',
                'method' => 'POST',
                'tipo' => 'form',
                'class_div' => "p-4 bg-light rounded shadow-sm h-100",
                'class_form' => 'row g-4 p-4 bg-light rounded shadow-sm',
                'class_tr' => 'p-4 bg-light rounded shadow-sm h-100',
                'class_th' => 'text-center',
                'class_td' => 'text-center',
                'class_table' => 'table table-striped table-bordered',
                'class_table_div' => 'row g-4 p-4 bg-light shadow-sm',
                'class_thead' => 'thead-light',
                'class_tbody' => 'container',
                'class_tfoot' => 'thead-light',
            ],
            'comandos' => [
               ],
               
            
            'campos' => [
                'nombre' => [
                    'nombre' => 'nombre',
                    'type' => 'text',
                    'label' => 'Nombre',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => true,
                    'placeholder' => 'Nombres',
                    'help' => 'Ingrese el nombre',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[A-Za-z0-9 ]{1,255}'
                ],
                'apellido' => [
                    'nombre' => 'apellido',
                    'type' => 'text',
                    'label' => 'Apellido',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => true,
                    'placeholder' => 'Apellido',
                    'help' => 'Ingrese apellido',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[A-Za-z0-9 ]{1,255}'
                ],
                'dni' => [
                    'nombre' => 'dni',
                    'type' => 'text',
                    'label' => 'DNI',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => true,
                    'placeholder' => 'DNI',
                    'help' => 'Ingrese DNI',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'direccion_calle' => [
                    'nombre' => 'direccion_calle',
                    'type' => 'text',
                    'label' => 'Calle',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Calle',
                    'help' => 'Ingrese calle',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[A-Za-z0-9 ]{1,255}'
                ],
                'direccion_numero' => [
                    'nombre' => 'direccion_numero',
                    'type' => 'text',
                    'label' => 'Número',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Número',
                    'help' => 'Ingrese número',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'direccion_piso' => [
                    'nombre' => 'direccion_piso',
                    'type' => 'text',
                    'label' => 'Piso',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Piso',
                    'help' => 'Ingrese piso',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'direccion_depto' => [
                    'nombre' => 'direccion_depto',
                    'type' => 'text',
                    'label' => 'Departamento',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Departamento',
                    'help' => 'Ingrese departamento',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    //'pattern' => '[A-Za-z0-9 ]{1,255}'
                ],
                'direccion_cp' => [
                    'nombre' => 'direccion_cp',
                    'type' => 'text',
                    'label' => 'Código Postal',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Código Postal',
                    'help' => 'Ingrese código postal',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'ciudad_id' => [
                    'nombre' => 'ciudad_id',
                    'type' => 'select',
                    'label' => 'Ciudad',
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Seleccione ciudad',
                    'help' => 'Seleccione ciudad',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'options' => 
			            [
                        'datasource'   => 'Ciudades',
                        'id_field'     => 'id',
                        'mostrarcampo' => ['nombre'], // sumá campos a gusto
                        'separator'    => '',
                        'where'        => '',
                        'params'       => [],
                        'order_by'     => 'label',
                        'collate'      => 'utf8mb4_spanish_ci',
                        ],
                ],
                'provincia_id' => [
                    'nombre' => 'provincia_id',
                    'type' => 'select',
                    'label' => 'Provincia',
                    'readonly' => false,
                    'hidden' => false,
                    'required' => true,
                    'placeholder' => 'Seleccione provincia',
                    'help' => 'Seleccione provincia',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'options' => 
			            [
                        'datasource'   => 'Provincias',
                        'id_field'     => 'id',
                        'mostrarcampo' => ['nombre'], // sumá campos a gusto
                        'separator'    => '',
                        'where'        => '',
                        'params'       => [],
                        'order_by'     => 'label',
                        'collate'      => 'utf8mb4_spanish_ci',
                        ],
                ],
                
                'telefono' => [
                    'nombre' => 'telefono',
                    'type' => 'text',
                    'label' => 'Teléfono',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Teléfono',
                    'help' => 'Ingrese teléfono',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'celular' => [
                    'nombre' => 'celular',
                    'type' => 'text',
                    'label' => 'Celular',
                    'maxlength' => 255,
                    'readonly' => false,
                    'hidden' => false,
                    'required' => false,
                    'placeholder' => 'Celular',
                    'help' => 'Ingrese celular',
                    'class' => 'form-control',
                    'style' => 'width: 100%;',
                    'autocomplete' => 'off',
                    'pattern' => '[0-9]{1,255}'
                ],
                'mailparticular' => [
                    'nombre' => 'mailparticular', 
                    'type' => 'mail', 
                    'label' => 'Mail particular', 
                    'placeholder' => 'Ingrese su dirección de e-mail', 
                    'readonly' => false, 
                    'hidden' => false, 
                    'help' => 'Ingrese mail de uso personal', 
                    'class' => 'form-control', 
                    'style' => 'width: 100%;', 
                    'autocomplete' => 'off', 
                    //'pattern' => '[A-Za-z0-9 ]{1,255}', 
                    'options' => [], 
                    'columna_rel' => '', 
                    'default' => 'NULL', 
                    'tabla_rel' => ''
                ],
	            'maillaboral' => [
                    'nombre' => 'maillaboral', 
                    'type' => 'mail', 
                    'label' => 'Mail laboral', 
                    'placeholder' => 'Ingrese dirección de e-mail (laboral)', 
                    'readonly' => false, 
                    'hidden' => false, 
                    'help' => 'Ingrese mail laboral', 
                    'class' => 'form-control', 
                    'style' => 'width: 100%;', 
                    'autocomplete' => 'off', 
                    //'pattern' => '[A-Za-z0-9 ]{1,255}', 
                    'options' => [], 
                    'columna_rel' => '', 
                    'default' => 'NULL', 
                    'tabla_rel' => ''
                ],

            ],
            'actividades' => [                
            ],

            
            'buttons' => [
                'cancel' => [
                    'type' => 'button',
                    'text' => 'Volver',
                    'url' => '',
                    'class' => 'btn btn-outline-secondary btn-rounded',
                    'icon' => 'bi bi-arrow-left',
                    'backbutton' => true, // para que funcione el botón de volver

                ],

            ],
];

