<?php    //delete confirmation view
return [
    'config' => [
        'title' => 'Cargos',
        'subtitle' => 'Eliminar registro',
        'url_action' => '/cargos/delete',
        'method' => 'POST',
        'tipo' => 'form',
        'class_div' => "p-4 bg-light rounded shadow-sm h-100",
        'class_form' => 'row g-4 p-4 bg-light rounded shadow-sm',
        'class_tr' => 'p-4 bg-light rounded shadow-sm h-100',
        'class_th' => 'text-center',
        'class_td' => 'text-center',
        'class_table' => 'table table-striped table-bordered',
        'class_table_div' => 'row g-4 p-4 bg-light shadow-sm',
        'class_thead' => 'thead-light',
        'class_tbody' => 'container',
        'class_tfoot' => 'thead-light',
        'field_id' => 'id',
    ],
    'comandos' => [
    ],
    'campos' => [
        'id' => [
            'nombre' => 'id',
            'type' => 'text',
            'label' => 'Id',
            'maxlength' => 11,
            'readonly' => true,
            'hidden' => true,
            'required' => false,
            'placeholder' => '',
            'help' => '',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
        'nombre' => [
            'nombre' => 'nombre',
            'type' => 'text',
            'label' => 'Nombre',
            'maxlength' => 50,
            'readonly' => true,
            'hidden' => false,
            'required' => false,
            'placeholder' => '',
            'help' => '',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
        'jerarquia' => [
            'nombre' => 'jerarquia',
            'type' => 'text',
            'label' => 'Jerarquia',
            'maxlength' => 11,
            'readonly' => true,
            'hidden' => false,
            'required' => false,
            'placeholder' => '',
            'help' => '',
            'class' => 'form-control',
            'style' => 'width: 100%;',
            'autocomplete' => 'off',
        ],
    ],
    'actividades' => [
    ],
    'buttons' => [
        'cancel' => [
            'type' => 'button',
            'text' => 'Volver',
            'url' => '',
            'class' => 'btn btn-outline-secondary btn-rounded',
            'icon' => 'bi bi-arrow-left',
            'backbutton' => true,
        ],
        'delete' => [
            'type' => 'submit',
            'text' => 'Eliminar registro',
            'class' => 'btn btn-danger btn-rounded',
            'icon' => 'bi bi-trash me-1',
        ],
    ],
];
